server:
  session-timeout: 1800
#    tomcat:
#        max-threads: 1000
#        min-spare-threads: 30
  port: 80
  context-path: /bootworld
#    uri-encoding: utf-8

spring:
  thymeleaf:
    mode: HTML
    cache: false
    check-template: true
    check-template-location: true
#    content-type: text/html
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: ALWAYS
    deserialization:
      fail-on-unknown-properties: false
    generator:
      write-bigdecimal-as-plain: true
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    parser:
      allow-unquoted-field-names: true
      allow-single-quotes: true
    serialization:
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
      write-enums-using-to-string: true
    time-zone: GMT+8
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: true
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
    dispatch-options-request: true
    static-path-pattern: /static/**
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
#    cache-period: 0
  cache:
    type: ehcache
    ehcache:
      config: classpath:config/ehcache.xml
security:
  basic:
    enabled: false
mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
  mapper-locations: classpath*:com/zfb/bootworld/**/mapper/*.xml
#  mapperLocations: classpath:com.zfb.bootworld/*/*Mapper.xml
#  typeAliasesPackage: com.zfb.bootworld.entity
#mappers 多个接口时逗号隔开
#mapper:
#  mappers: tk.mybatis.mapper.common.Mapper,tk.mybatis.mapper.common.special.InsertListMapper
#  not-empty: false
#  identity: MYSQL
##pagehelper分页插件配置
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
#[弃用]配置缓存和session存储方式，默认ehcache,可选redis,[弃用]调整至 spring cache type【shiro.用户，权限，session，spring.cache通用】
#[弃用]cacheType: ehcache
